// Generated by dts-bundle-generator v9.5.1

declare const opaque: unique symbol;
/**
 * Type that is tagged to distinguish it from the underlying untagged type.
 *
 * The type `Opaque<Value, Tag>` is equivalent to `Value` but is "tagged" with type `Tag` so that it is structurally distinct from `Value`.
 */
export type Opaque<Value, Tag> = Value & {
	/**
	 * @ignore
	 * @hidden
	 */
	[opaque]: Tag;
};
declare const t: unique symbol;
export type T<V> = {
	[t]: V;
};
declare const _Void: unique symbol;
export type Void = T<typeof _Void>;
declare const _Byte: unique symbol;
export type Byte = T<typeof _Byte>;
declare const _Uint32: unique symbol;
export type UInt32 = T<typeof _Uint32>;
declare const _Float: unique symbol;
export type Float = T<typeof _Float>;
declare const _String: unique symbol;
export type SKString = T<typeof _String>;
declare const _Exception: unique symbol;
export type Exception = T<typeof _Exception>;
declare const p: unique symbol;
declare const _Array: unique symbol;
export type SKArray<Ty extends T<any>> = T<typeof _Array> & {
	[p]: (_: Ty) => Ty;
};
declare const _Vector: unique symbol;
export type SKVector<Ty extends T<any>> = T<typeof _Vector> & {
	[p]: (_: Ty) => Ty;
};
declare const _Pair: unique symbol;
export type SKPair<Ty1 extends T<any>, Ty2 extends T<any>> = T<typeof _Pair> & {
	[p]: [
		Ty1,
		Ty2
	];
};
declare const _Function: unique symbol;
export type SKFunction<Ty1 extends T<any>, Ty2 extends T<any>> = T<typeof _Function> & {
	[p]: (_: Ty1) => Ty2;
};
declare const skpointer: unique symbol;
export interface Pointer<InternalType extends T<any>> {
	[skpointer]: InternalType;
}
export type float = number;
export type int = number;
/**
 * Potentially `null` values.
 *
 * The type `Nullable<T>` of potentially `null` values of type `T`.
 */
export type Nullable<T> = T | null;
export type ptr<InternalType extends T<any>> = Opaque<number, InternalType> & Pointer<InternalType>;
declare enum Stream {
	OUT = 0,
	ERR = 1,
	DEBUG = 2
}
declare class State {
	exceptionId: number;
	exceptions: Map<number, Exception$1>;
}
declare class Exception$1 {
	id: int;
	err: Error;
	constructor(err: Error, state: State);
}
export interface Shared {
	getName: () => string;
}
declare class Options {
	read: boolean;
	write: boolean;
	append: boolean;
	truncate: boolean;
	create: boolean;
	create_new: boolean;
	constructor(read?: boolean, write?: boolean, append?: boolean, truncate?: boolean, create?: boolean, create_new?: boolean);
	static w(): Options;
	toFlags(): number;
	static fromFlags(flags: int): Options;
}
export interface SKFileSystem {
	openFile(filename: string, flags: Options, mode: int): number;
	closeFile(fd: int): void;
	watchFile(filename: string, f: (change: string) => void): void;
	writeToFile(fd: int, content: string): void;
	appendToFile(filename: string, content: string): void;
	write(fd: int, content: string): int;
	read(fd: int, len: int): string | null;
	exists(filename: string): boolean;
}
export interface System {
	setenv(name: string, value: string): void;
	getenv(name: string): string | null;
	unsetenv(name: string): void;
}
export interface Environment {
	shared: Map<string, Shared>;
	name: () => string;
	disableWarnings: boolean;
	environment: string[];
	timestamp: () => float;
	decodeUTF8: (utf8: ArrayBuffer) => string;
	encodeUTF8: (str: string) => Uint8Array;
	onException: () => void;
	base64Decode: (base64: string) => Uint8Array;
	base64Encode: (toEncode: string, url?: boolean) => string;
	fs: () => SKFileSystem;
	sys: () => System;
	crypto: () => Crypto;
	fetch: (url: URL | string) => Promise<Uint8Array | ArrayBuffer>;
}
declare class Utils {
	private readonly exports;
	private readonly env;
	private readonly state;
	private readonly states;
	args: string[];
	private current_stdin;
	private stdin;
	private stdout;
	private stderr;
	private stddebug;
	private readonly mainFn?;
	private exception?;
	private stacks;
	exit: (code: int) => never;
	constructor(exports: WebAssembly.Exports, env: Environment, mainFn?: string);
	log: (str: string, kind?: Stream, newLine?: boolean) => void;
	sklog: (strPtr: ptr<SKString>, kind?: Stream, newLine?: boolean) => void;
	clearMainEnvironment: (new_args?: string[], new_stdin?: string) => void;
	runCheckError: <T>(fn: () => T) => T;
	main: (new_args: string[], new_stdin: string) => string;
	importOptString: (strPtr: ptr<SKString>) => string | null;
	importString: (strPtr: ptr<SKString>) => string;
	exportString: (s: string) => ptr<SKString>;
	importBytes: (skArray: ptr<SKArray<Byte>>, sizeof?: int) => Uint8Array<ArrayBuffer>;
	importBytes2: (skBytes: ptr<T<any>>, size?: int) => Uint8Array<ArrayBuffer>;
	exportBytes: (view: Uint8Array) => ptr<SKArray<Byte>>;
	exportBytes2: (view: Uint8Array, skBytes: ptr<T<any>>) => void;
	importUInt32s: (skArray: ptr<SKArray<UInt32>>) => Uint32Array<ArrayBuffer>;
	exportUInt32s(array: Uint32Array): ptr<SKArray<UInt32>>;
	importFloats: (skArray: ptr<SKArray<Float>>) => Float64Array<ArrayBuffer>;
	exportFloats(array: Float64Array): ptr<SKArray<Float>>;
	call: <Ret>(fnId: ptr<SKFunction<Void, T<Ret>>>) => ptr<T<Ret>>;
	callWithException: <Ret>(fnId: ptr<SKFunction<Void, T<Ret>>>, exception: Exception$1 | null) => ptr<T<Ret>>;
	getBytesFromBuffer: (dataPtr: ptr<T<any>>, length: int) => Uint8ClampedArray<ArrayBuffer>;
	init: () => void;
	etry: <Ret>(f: ptr<SKFunction<Void, T<Ret>>>, exn_handler: ptr<SKFunction<Void, T<Ret>>>) => ptr<T<Ret>>;
	ethrow: (skExc: ptr<Exception>, rethrow: boolean) => never;
	replace_exn(oldex: ptr<Exception>, newex: ptr<Exception>): void;
	deleteException: (exc: int) => void;
	getExceptionMessage: (exc: int) => string;
	getExceptionStack: (exc: int) => string;
	getErrorObject: (skExc: ptr<Exception>) => Error;
	getPersistentSize: () => number;
	getVersion: () => number;
	getMemoryBuffer: () => ArrayBuffer;
	readStdInLine: () => number[];
	readStdInToEnd: () => number[];
	runWithGc: <T>(fn: () => T) => T;
	getState<T>(name: string, create: () => T): T;
}
export interface UiText {
	toJSON: () => object;
}
declare const _JSON: unique symbol;
export type IJson<Sub = any, Sub2 = any> = T<typeof _JSON> & {
	sub: Sub;
	sub2: Sub2;
};
declare const _JSArray: unique symbol;
export type IJSArray<Sub extends IJson = IJson> = IJson<typeof _JSArray, Sub>;
declare const _JSObject: unique symbol;
export type IJSObject = IJson<typeof _JSObject>;
export type IPartialJSObj = SKVector<SKPair<SKString, IJson>>;
export type PartialJSArray<T extends IJson> = SKVector<T>;
export type Handle<T> = Opaque<number, {
	handle_for: T;
}>;
export type Json = boolean | number | string | JsonArray | JsonObject | JSObject | RenderableElement;
export type JsonObject = {
	[key: string]: Json | null;
};
export type JsonArray = (Json | null)[];
export type Combine = (combine: (values: JsonArray) => Json, combinables: Readable[], write?: (value: Json) => void) => Property;
export interface Readable {
	get: () => Nullable<Json>;
}
export interface Writable {
	set: (value: Json) => void;
}
export interface Property extends Writable, Readable {
}
export declare enum Alignment {
	Start = 0,
	End = 1,
	Center = 2,
	SpaceBetween = 3,
	SpaceAround = 4,
	SpaceEvenly = 5
}
export declare enum FlCrossAlign {
	Start = 0,
	End = 1,
	Center = 2,
	Stretch = 3
}
export declare enum WrCrossAlign {
	Start = 0,
	End = 1,
	Center = 2
}
export declare enum Fit {
	Loose = 0,
	Expend = 1,
	Passthrough = 2
}
export declare enum ButtonKind {
	Regular = 0,
	Primary = 1,
	Accent = 2,
	Warm = 3
}
export declare enum ButtonMode {
	Basic = 0,
	Stroked = 1,
	Raised = 2,
	Flat = 3,
	Icon = 4,
	MiniIcon = 5,
	Fab = 6,
	MiniFab = 7
}
export declare enum IconType {
	Inner = 0,
	Theme = 1,
	Image = 2
}
export declare enum InputType {
	UiText = 0,
	Password = 1,
	ASCII = 2,
	Integer = 3,
	Real = 4,
	Hex = 5,
	Binary = 6,
	Octal = 7,
	Pattern = 8
}
export declare enum Level {
	Information = 0,
	Warning = 1,
	Error = 2
}
export declare enum StatusType {
	OK = 0,
	VALID = 1,
	RUNNING = 2,
	KO = 3
}
export declare enum SepType {
	FromStart = 0,
	FromEnd = 1,
	Percent = 2
}
export declare enum ToggleKind {
	Toggle = 0,
	Checkbox = 1,
	Radio = 2
}
export declare enum Policy {
	Always = 0,
	AsNeeded = 1,
	Never = 2,
	Hidden = 3
}
export declare enum HAlignment {
	Center = 0,
	Justify = 1,
	Left = 2,
	Right = 3
}
export declare enum VAlignment {
	Top = 0,
	Middle = 1,
	Bottom = 2
}
export declare enum Wrapping {
	No = 0,
	Char = 1,
	Word = 2
}
export declare enum Transform {
	No = 0,
	Uppercase = 1,
	Lowercase = 2,
	UppercaseFirst = 3,
	Capitalize = 4
}
export declare enum Overflow {
	LeadingChar = 0,
	CenterChar = 1,
	EndingChar = 2,
	LeadingWord = 3,
	CenterWord = 4,
	EndingWord = 5
}
export declare enum Slant {
	Normal = 0,
	Italic = 1
}
export declare enum Drop {
	Before = 0,
	After = 1,
	In = 2
}
export declare enum Weight {
	Thin = 100,
	ExtraLight = 200,
	Light = 300,
	Normal = 400,
	Medium = 500,
	SemiBold = 600,
	Bold = 700,
	ExtraBold = 800,
	Black = 900
}
export declare enum TabsKind {
	Fixed = 0,
	Scrollable = 1
}
export declare enum TabsMode {
	Basic = 0,
	Flat = 1
}
export declare enum Side {
	Left = 0,
	Top = 1,
	Right = 2,
	Bottom = 3
}
export declare enum Order {
	Asc = 0,
	Desc = 1,
	None = 2
}
export declare enum Separator {
	None = 0,
	Before = 1,
	After = 2,
	Both = 3
}
export type IconKind = string | IconType;
export type Value<T> = T | Readable;
export declare class JSObject {
	type: string;
	fields: object;
	constructor(type: string, fields: object);
	toJSON(): JsonObject;
}
export declare class WidgetElement extends JSObject {
}
export declare class IconElement extends JSObject {
}
export declare class Configuration extends JSObject {
}
export declare class Decoration extends JSObject {
}
export declare class RangeElement extends JSObject {
}
export declare class InputKindElement extends JSObject {
}
export declare class SeparationElement extends JSObject {
}
export declare class StatusElement extends JSObject {
}
export declare class InsetsElement extends JSObject {
}
export declare class ConstraintsElement extends JSObject {
}
export declare class TextStyleElement extends JSObject {
}
export declare class IconedActionElement extends JSObject {
}
export declare class TabElement extends JSObject {
}
export declare class TreeItemElement extends JSObject {
}
export declare class DropdownElement extends JSObject {
}
export declare class ShorcutElement extends JSObject {
}
export declare class DialogElement extends JSObject {
}
export declare class RenderableElement {
	renderable: Renderable;
	constructor(renderable: Renderable);
}
export type Widget = WidgetElement | RenderableElement;
export type FlexConf = {
	flex?: int;
	"fit-loose"?: boolean;
	"ignore-cross"?: boolean;
};
export type Flex = {
	children: Value<Value<Widget>[]>;
	vertical?: Value<boolean>;
	"main-reversed"?: Value<boolean>;
	"cross-reversed"?: Value<boolean>;
	"main-alignment"?: Value<Alignment>;
	"cross-alignment"?: Value<FlCrossAlign>;
	"max-size"?: Value<boolean>;
	configuration?: Value<Configuration>;
};
export type Wrap = {
	children: Value<Value<Widget>[]>;
	vertical?: Value<boolean>;
	"main-reversed"?: Value<boolean>;
	"cross-reversed"?: Value<boolean>;
	"main-alignment"?: Value<Alignment>;
	"cross-alignment"?: Value<WrCrossAlign>;
	"run-alignment"?: Value<Alignment>;
	spacing?: Value<int>;
	"run-spacing"?: Value<int>;
	configuration?: Value<Configuration>;
};
export type StackConf = {
	fit?: Fit;
	opaque?: boolean;
};
export type Stack = {
	children: Value<Value<Widget>[]>;
	configuration?: Value<Configuration>;
};
export type AspectRatio = {
	child: Value<Widget>;
	ratio?: Value<float>;
	centered?: Value<boolean>;
	configuration?: Value<Configuration>;
};
export type Icon = {
	kind: IconKind;
	name: string;
};
export type Button = {
	"on-fire": (count: int) => void;
	kind?: ButtonKind;
	mode?: ButtonMode;
	text?: Value<string | UiText>;
	icon?: Value<IconElement>;
	tooltip?: Value<string | UiText>;
	disabled?: Value<boolean>;
	configuration?: Value<Configuration>;
};
export type Slider = {
	value: Property;
	bounds: Value<RangeElement>;
	range?: Value<boolean>;
	vertical?: Value<boolean>;
	step?: Value<int>;
	disabled?: Value<boolean>;
	small?: Value<boolean>;
	labeled?: Value<boolean>;
	ticks?: Value<int>;
	configuration?: Value<Configuration>;
};
export type InputKind = {
	type: InputType;
	min?: number;
	max?: number;
	pattern?: string;
};
export type Status = {
	type: StatusType;
	error?: string;
	level?: Level;
	progress?: int;
};
export type Input = {
	kind?: InputKindElement;
	"max-chars"?: int;
	"visible-chars"?: int;
	"on-action"?: (text: string) => void;
	"on-focus-lost"?: (text: string) => void;
	label?: Value<string | UiText>;
	icon?: Value<IconElement>;
	prefix?: Value<string | UiText>;
	suffix?: Value<string | UiText>;
	placeholder?: Value<string | UiText>;
	tooltip?: Value<string | UiText>;
	"action-icon"?: Value<IconElement>;
	disabled?: Value<boolean>;
	editable?: Value<boolean>;
	"with-counter"?: Value<boolean>;
	"with-status"?: Value<boolean>;
	"with-label"?: Value<boolean>;
	"with-clear"?: Value<boolean>;
	"align-right"?: Value<boolean>;
	"placeholder-as-label"?: Value<boolean>;
	text?: Value<string | UiText>;
	position?: Value<int>;
	selection?: Value<RangeElement>;
	status?: Value<StatusElement>;
	configuration?: Value<Configuration>;
};
export type Separation = {
	value: int;
	type?: SepType;
};
export type Split = {
	first: Value<Widget>;
	second: Value<Widget>;
	separation: Value<SeparationElement>;
	vertical?: Value<boolean>;
	configuration?: Value<Configuration>;
};
export type Toggle = {
	selected: Readable;
	kind?: Value<ToggleKind>;
	text?: Value<string | UiText>;
	icon?: Value<IconElement>;
	tooltip?: Value<string | UiText>;
	disabled?: Value<boolean>;
	indeterminate?: Readable;
	configuration?: Value<Configuration>;
};
export type Scroll = {
	widget: Value<Widget>;
	"h-scroll"?: Value<int>;
	"v-scroll"?: Value<int>;
	"h-policy"?: Value<Policy>;
	"v-policy"?: Value<Policy>;
	unit?: Value<int>;
	negative?: Value<boolean>;
	configuration?: Value<Configuration>;
};
export type Insets = {
	start?: string;
	left?: string;
	top?: string;
	end?: string;
	right?: string;
	bottom?: string;
};
export type Background = {
	color: string;
	padding?: InsetsElement;
	radius?: string;
};
export type Padding = {
	padding?: InsetsElement;
};
export type BorderLine = {
	color: string;
	padding?: InsetsElement;
};
export type Nested = {
	decorations: Decoration[];
};
export type Constraints = {
	"min-width"?: string;
	"max-width"?: string;
	"min-height"?: string;
	"max-height"?: string;
};
export type Label = {
	text?: Value<string | UiText>;
	icon?: Value<IconElement>;
	tooltip?: Value<string | UiText>;
	configuration?: Value<Configuration>;
};
export type Indicator = {
	progress?: Value<int>;
	configuration?: Value<Configuration>;
};
export type Decorated = {
	decoration: Value<Decoration>;
	child?: Value<Widget>;
	"rigth-to-left"?: Value<boolean>;
	configuration?: Value<Configuration>;
};
export type Constrained = {
	constraints: Value<ConstraintsElement>;
	child?: Value<Widget>;
	enforced?: Value<boolean>;
	configuration?: Value<Configuration>;
};
export type TextStyle = {
	color?: string;
	size?: string;
	slant?: Slant;
	weight?: Weight;
	"h-alignment"?: HAlignment;
	"v-alignment"?: VAlignment;
	"line-spacing"?: string;
	wrapping?: Wrapping;
	overflow?: Overflow;
	transform?: Transform;
};
export type TextView = {
	text: Value<string | UiText>;
	style: Value<TextStyleElement>;
	configuration?: Value<Configuration>;
};
export type IconedAction = {
	id: string;
	icon: Value<IconElement>;
	"on-fire": () => void;
	tooltip?: Value<string | UiText>;
	disabled?: Value<boolean>;
};
export type Tab = {
	id: string;
	widget: Value<Widget>;
	icon?: Value<IconElement>;
	text?: Value<string | UiText>;
	discriminant?: Value<string | UiText>;
	tooltip?: Value<string | UiText>;
	disabled?: Value<boolean>;
	badge?: Value<string | UiText>;
	progress?: Value<int>;
	closable?: Value<boolean>;
};
export type Tabs = {
	tabs?: Value<TabElement[]>;
	actions?: Value<IconedActionElement[]>;
	active?: Value<string>;
	kind?: Value<TabsKind>;
	mode?: Value<TabsMode>;
	side?: Value<Side>;
	placeholder?: Value<string | UiText>;
	"icon-on-top"?: Value<boolean>;
	"min-width"?: Value<int> | int;
	"max-width"?: Value<int> | int;
	configuration?: Value<Configuration>;
};
export type TreeItem = {
	text: string;
	icon?: IconElement;
	tooltip?: string;
	id?: string;
	items?: Value<TreeItemElement[]>;
};
export type Shortcut = {
	key: string;
	ctrl: boolean;
	shift: boolean;
	alt: boolean;
	meta: boolean;
};
export type DropdownItem = {
	id: string;
	text: string;
	icon?: IconElement;
	tooltip?: string;
	disabled: boolean;
	separator: Separator;
	shortcut?: ShorcutElement;
	perform: () => void;
};
export type DropdownSupplier = () => DropdownElement[];
export type DropdownMenu = {
	id: string;
	text: string;
	icon?: IconElement;
	tooltip?: string;
	disabled: boolean;
	separator: Separator;
	items: DropdownElement[] | DropdownSupplier;
};
export type Tree = {
	items: Value<TreeItemElement[]>;
	"on-expansion-change"?: (path: string[], value: boolean) => void;
	"on-selection-change"?: (selection: string[][]) => void;
	"on-tree-perform"?: (current: string[], selection: string[][]) => void;
	"on-tree-drop"?: (from: string[][], to: string[], drop: Drop) => void;
	"get-context-menu"?: (current: string[], selection: string[][]) => DropdownElement[];
	"allow-multiple-selection"?: Value<boolean>;
	"badge-max-char"?: Value<int>;
	configuration?: Value<Configuration>;
};
export type Renderable = (scope: Scope) => Widget;
export declare const flexConf: (conf: FlexConf) => Configuration;
export declare const stackConf: (conf: StackConf) => Configuration;
export declare const icon: (setting: Icon) => IconElement;
export declare const range: (start: int, end: int) => RangeElement;
export declare const inputKind: (setting: InputKind) => InputKindElement;
declare const status$1: (setting: Status) => StatusElement;
export declare const separation: (setting: Separation) => SeparationElement;
export declare const insets: (setting: Insets) => InsetsElement;
export declare const constraints: (setting: Constraints) => ConstraintsElement;
export declare const textStyle: (setting: TextStyle) => TextStyleElement;
export declare const shortcut: (setting: Shortcut) => ShorcutElement;
export declare const background: (setting: Background) => Decoration;
export declare const padding: (setting: Padding) => Decoration;
export declare const borderLine: (setting: BorderLine) => Decoration;
export declare const nested: (setting: Nested) => Decoration;
export declare const iconedAction: (setting: IconedAction) => IconedActionElement;
export declare const tab: (setting: Tab) => TabElement;
export declare const treeItem: (setting: TreeItem) => TreeItemElement;
export declare const dropdownitem: (setting: DropdownItem) => DropdownElement;
export declare const dropdownmenu: (setting: DropdownMenu) => DropdownElement;
export declare const flex: (setting: Flex) => WidgetElement;
export declare const wrap: (setting: Wrap) => WidgetElement;
export declare const stack: (setting: Stack) => WidgetElement;
export declare const button: (setting: Button) => WidgetElement;
export declare const slider: (setting: Slider) => WidgetElement;
export declare const input: (setting: Input) => WidgetElement;
export declare const split: (setting: Split) => WidgetElement;
export declare const toggle: (setting: Toggle) => WidgetElement;
declare const scroll$1: (setting: Scroll) => WidgetElement;
export declare const label: (setting: Label) => WidgetElement;
export declare const indicator: (setting: Indicator) => WidgetElement;
export declare const decorated: (setting: Decorated) => WidgetElement;
export declare const constrained: (setting: Constrained) => WidgetElement;
export declare const textView: (setting: TextView) => WidgetElement;
export declare const tabs: (setting: Tabs) => WidgetElement;
export declare const tree: (setting: Tree) => WidgetElement;
export declare const insetsAll: (thickness: string) => InsetsElement;
export declare const paddingAll: (thickness: string) => Decoration;
export declare const renderable: (renderable: Renderable) => RenderableElement;
export interface Scope {
	alert(text: string | UiText, title: Nullable<string | UiText>): void;
	dialog(dialog: JSObject): void;
	create(value?: Json): Property;
	combine(combine: (values: JsonArray) => Json, combinables: Readable[], write?: (value: Json) => void): Property;
}
export interface Exports {
	SKIP_UiEngineJS_register(id: int, path: Nullable<ptr<SKString>>, type_: ptr<SKString>): void;
	SKIP_UiEngineJS_toJS(json: ptr<IJson>): Handle<Json>;
	SKIP_JSON_startObject(): ptr<IPartialJSObj>;
	SKIP_JSON_addToObject(obj: ptr<IPartialJSObj>, name: ptr<SKString>, value: ptr<IJson>): void;
	SKIP_JSON_endObject(obj: ptr<IPartialJSObj>): ptr<IJSObject>;
	SKIP_JSON_startArray(): ptr<PartialJSArray<IJson>>;
	SKIP_JSON_addToArray(arr: ptr<PartialJSArray<IJson>>, value: ptr<IJson>): void;
	SKIP_JSON_endArray(arr: ptr<PartialJSArray<IJson>>): ptr<IJSArray<IJson>>;
	SKIP_JSON_createNull(): ptr<IJson>;
	SKIP_JSON_createIntNumber(v: int): ptr<IJson>;
	SKIP_JSON_createFloatNumber(v: float): ptr<IJson>;
	SKIP_JSON_createString(str: ptr<SKString>): ptr<IJson>;
	SKIP_JSON_createBool(v: boolean): ptr<IJson>;
}
export type JSONFunction = <T extends Json, P extends JsonArray>(..._: P) => T;
declare class State$1 {
	private nextID;
	private readonly objects;
	private readonly freeIDs;
	register<T>(v: T): Handle<T>;
	get<T>(id: Handle<T>): T;
	apply<R>(id: Handle<(..._: JsonArray) => R>, parameters: JsonArray): R;
	delete<T>(id: Handle<T>): T;
}
export declare class EngShared implements Shared {
	getName: () => string;
	createScope: (data: string) => Scope;
	constructor(createScope: (data: string) => Scope);
}
export declare class SkuiEngUtils {
	utils: Utils;
	exports: Exports;
	state: State$1;
	createScope: (name: string) => Scope;
	constructor(utils: Utils, exports: any, createScope: (name: string) => Scope, state?: State$1);
	importValue(value: ptr<IJson>): Json;
	register<R, P extends any[]>(skPath: Nullable<ptr<SKString>>, value: (..._: P) => R): Handle<(..._: P) => R>;
	exportValue(path: Nullable<string>, skPath: Nullable<ptr<SKString>>, value: Json | JSONFunction | null): ptr<IJson>;
}
declare const themify = "themify";
declare const ArrowLeft: IconElement;
declare const ArrowUp: IconElement;
declare const ArrowRight: IconElement;
declare const ArrowDown: IconElement;
declare const ArrowTopLeft: IconElement;
declare const ArrowTopRight: IconElement;
declare const ArrowCircleLeft: IconElement;
declare const ArrowCircleUp: IconElement;
declare const ArrowCircleRight: IconElement;
declare const ArrowCircleDown: IconElement;
declare const ArrowsHorizontal: IconElement;
declare const ArrowsVertical: IconElement;
declare const ArrowsCorner: IconElement;
declare const AngleLeft: IconElement;
declare const AngleUp: IconElement;
declare const AngleRight: IconElement;
declare const AngleDown: IconElement;
declare const DoubleAngleLeft: IconElement;
declare const DoubleAngleUp: IconElement;
declare const DoubleAngleRight: IconElement;
declare const DoubleAngleDown: IconElement;
declare const Move: IconElement;
declare const Fullscreen: IconElement;
declare const Redo: IconElement;
declare const ExchangeVertical: IconElement;
declare const Save: IconElement;
declare const Direction: IconElement;
declare const MultipleDirection: IconElement;
declare const User: IconElement;
declare const Link: IconElement;
declare const Unlink: IconElement;
declare const Trash: IconElement;
declare const Target: IconElement;
declare const Tag: IconElement;
declare const Desktop: IconElement;
declare const Tablet: IconElement;
declare const Mobile: IconElement;
declare const Email: IconElement;
declare const Star: IconElement;
declare const Signal: IconElement;
declare const ShoppingCart: IconElement;
declare const Settings: IconElement;
declare const Search: IconElement;
declare const ZoomIn: IconElement;
declare const ZoomOut: IconElement;
declare const Cut: IconElement;
declare const Bookmark: IconElement;
declare const Bookmarked: IconElement;
declare const Reload: IconElement;
declare const Plus: IconElement;
declare const Minus: IconElement;
declare const Close: IconElement;
declare const Pin: IconElement;
declare const Pencil: IconElement;
declare const Forbiden: IconElement;
declare const Lock$1: IconElement;
declare const Unlock: IconElement;
declare const LocationArrow: IconElement;
declare const Layout: IconElement;
declare const Layers: IconElement;
declare const Key: IconElement;
declare const Image$1: IconElement;
declare const Heart: IconElement;
declare const HeartBroken: IconElement;
declare const HandStop: IconElement;
declare const HandOpen: IconElement;
declare const HandDrag: IconElement;
declare const Flag: IconElement;
declare const Eye: IconElement;
declare const Import: IconElement;
declare const Export: IconElement;
declare const Comment$1: IconElement;
declare const Clip: IconElement;
declare const Check: IconElement;
declare const CheckBox: IconElement;
declare const Briefcase: IconElement;
declare const Bolt: IconElement;
declare const Dashboard: IconElement;
declare const World: IconElement;
declare const Timer: IconElement;
declare const Time: IconElement;
declare const ThumbUp: IconElement;
declare const ThumbDown: IconElement;
declare const PowerOff: IconElement;
declare const Map$1: IconElement;
declare const Menu: IconElement;
declare const Filter: IconElement;
declare const Clipboard$1: IconElement;
declare const Copy: IconElement;
declare const Info: IconElement;
declare const Home: IconElement;
declare const Help: IconElement;
declare const Alert: IconElement;
declare const Anchor: IconElement;
declare const Archive: IconElement;
declare const Cloud: IconElement;
declare const CloudUp: IconElement;
declare const CloudDown: IconElement;
declare const File$1: IconElement;
declare const Files: IconElement;
declare const Folder: IconElement;
declare const Zip: IconElement;
declare const More: IconElement;
declare const Occulted: IconElement;
declare const Share: IconElement;
declare const Calendar: IconElement;
declare const Paste: IconElement;
declare const Volume: IconElement;
export declare function launch(title: string, renderer: Renderable): Promise<void>;

declare namespace icons {
	export { Alert, Anchor, AngleDown, AngleLeft, AngleRight, AngleUp, Archive, ArrowCircleDown, ArrowCircleLeft, ArrowCircleRight, ArrowCircleUp, ArrowDown, ArrowLeft, ArrowRight, ArrowTopLeft, ArrowTopRight, ArrowUp, ArrowsCorner, ArrowsHorizontal, ArrowsVertical, Bolt, Bookmark, Bookmarked, Briefcase, Calendar, Check, CheckBox, Clip, Clipboard$1 as Clipboard, Close, Cloud, CloudDown, CloudUp, Comment$1 as Comment, Copy, Cut, Dashboard, Desktop, Direction, DoubleAngleDown, DoubleAngleLeft, DoubleAngleRight, DoubleAngleUp, Email, ExchangeVertical, Export, Eye, File$1 as File, Files, Filter, Flag, Folder, Forbiden, Fullscreen, HandDrag, HandOpen, HandStop, Heart, HeartBroken, Help, Home, Image$1 as Image, Import, Info, Key, Layers, Layout, Link, LocationArrow, Lock$1 as Lock, Map$1 as Map, Menu, Minus, Mobile, More, Move, MultipleDirection, Occulted, Paste, Pencil, Pin, Plus, PowerOff, Redo, Reload, Save, Search, Settings, Share, ShoppingCart, Signal, Star, Tablet, Tag, Target, ThumbDown, ThumbUp, Time, Timer, Trash, Unlink, Unlock, User, Volume, World, Zip, ZoomIn, ZoomOut, themify };
}

export {
	State$1 as State,
	icons,
	scroll$1 as scroll,
	status$1 as status,
};

export {};
