module alias T = SKTest;

module TestJava;

fun expectBuffer(
  buffer: readonly Vector<String>,
  expected: Vector<String>,
): void {
  T.expectEq(buffer.join("").split("\n"), expected);
}

@test
fun literal1(): void {
  buffer = mutable Vector[];
  i = Java.Literal("0L");
  i.print(buffer.push);
  expectBuffer(buffer, Vector["0L"]);
}

@test
fun narity1(): void {
  buffer = mutable Vector[];
  i = Java.NArityOp("+", Array[Java.Literal("x"), Java.Literal("2L")]);
  i.print(buffer.push);
  expectBuffer(buffer, Vector["x + 2L"]);
}

@test
fun narity2(): void {
  buffer = mutable Vector[];
  i = Java.NArityOp(
    "+",
    Array[
      Java.Literal("x"),
      Java.NArityOp("*", Array[Java.Literal("y"), Java.Literal("z")]),
    ],
  );
  i.print(buffer.push);
  expectBuffer(buffer, Vector["x + (y * z)"]);
}

@test
fun call1(): void {
  buffer = mutable Vector[];
  i = Java.Call(
    "c",
    "foo",
    Array[
      Java.Literal("x"),
      Java.NArityOp("*", Array[Java.Literal("y"), Java.Literal("z")]),
    ],
  );
  i.print(buffer.push);
  expectBuffer(buffer, Vector["c.foo(x, y * z)"]);
}

@test
fun ifthenelse(): void {
  buffer = mutable Vector[];
  i = Java.IfThenElse(
    Java.Literal("c"),
    Java.NArityOp("+", Array[Java.Literal("x"), Java.Literal("y")]),
    Java.IfThenElse(
      Java.Literal("b"),
      Java.Literal("1.0"),
      Java.Literal("2.0"),
    ),
  );
  i.print(buffer.push);
  expectBuffer(buffer, Vector["c ? (x + y) : (b ? 1.0 : 2.0)"]);
}

@test
fun equation1(): void {
  buffer = mutable Vector[];
  i = Java.Equation{
    name => "d",
    type => Java.Type{name => "int"},
    expression => Java.Call(
      "c",
      "foo",
      Array[
        Java.Literal("x"),
        Java.NArityOp("*", Array[Java.Literal("y"), Java.Literal("z")]),
      ],
    ),
  };
  i.print(buffer.push);
  expectBuffer(buffer, Vector["int d = c.foo(x, y * z)"]);
}

@test
fun interface1(): void {
  buffer = mutable Vector[];
  i = Java.Interface{
    package => Array["io", "skiplabs"],
    name => "A",
    signatures_ => Array[
      Java.Signature{
        name => "getField1",
        type => Java.Type{name => "int"},
        static_ => false,
      },
    ],
  };
  i.print(buffer.push);
  expectBuffer(
    buffer,
    Vector[
      "package io.skiplabs;",
      "",
      "public interface A {",
      "",
      "  public int getField1();",
      "}",
    ],
  );
}

@test
fun interface2(): void {
  buffer = mutable Vector[];
  i = Java.Interface{
    package => Array["io", "skiplabs"],
    imports => SortedSet["java.util.*"],
    name => "B",
    extends_ => Array[Java.Type{name => "C"}],
    types => Array[Java.Type{name => "T"}],
    signatures_ => Array[
      Java.Signature{
        name => "getField1",
        type => Java.Type{name => "int"},
        static_ => false,
      },
      Java.Signature{
        name => "getField2",
        type => Java.Type{name => "A", types => Array[Java.Type{name => "T"}]},
        static_ => false,
      },
    ],
  };
  i.print(buffer.push);
  expectBuffer(
    buffer,
    Vector[
      "package io.skiplabs;",
      "",
      "import java.util.*;",
      "",
      "public interface B<T>",
      "  extends C {",
      "",
      "  public int getField1();",
      "",
      "  public A<T> getField2();",
      "}",
    ],
  );
}

@test
fun class1(): void {
  buffer = mutable Vector[];
  i = Java.Class_{
    package => Array["io", "skiplabs"],
    imports => SortedSet["java.util.*"],
    name => "B",
    extends_ => Some(Java.Type{name => "C"}),
    implements => Array[Java.Type{name => "A"}],
    types => Array[Java.Type{name => "T"}],
    fields => Array[
      Java.Field{name => "field1", type => Java.Type{name => "int"}},
      Java.Field{
        name => "field2",
        type => Java.Type{name => "A", types => Array[Java.Type{name => "T"}]},
      },
    ],
    methods => Array[
      Java.Method{
        signature => Java.Signature{
          name => "getField1",
          type => Java.Type{name => "int"},
          static_ => false,
        },
        body => Java.Block{return_ => Some(Java.Access("this", "field1"))},
      },
      Java.Method{
        signature => Java.Signature{
          name => "getField2",
          type => Java.Type{
            name => "A",
            types => Array[Java.Type{name => "T"}],
          },
          static_ => false,
        },
        body => Java.Block{return_ => Some(Java.Access("this", "field2"))},
      },
    ],
  };
  i.print(buffer.push);
  expectBuffer(
    buffer,
    Vector[
      "package io.skiplabs;",
      "",
      "import java.util.*;",
      "",
      "public class B<T>",
      "  implements A",
      "  extends C {",
      "",
      "  public final int field1;",
      "  public final A<T> field2;",
      "",
      "  public int getField1(){",
      "    return this.field1;",
      "  }",
      "",
      "  public A<T> getField2(){",
      "    return this.field2;",
      "  }",
      "}",
    ],
  );
}

module end;
